- name: Register Legal Entities
  page: register.html
  image: fa-gem
  description:
  - Proprietorship
  - Partnership Firm
  - Limited Liability Partnership
  - One Person Company
  - Private Limited Company
- name: Accounting
  page: accounting.html
  image: fa-laptop-code
  description: 
  - Accounting and book keeping
- name: Tax Filing
  page: tax.html
  image: fa-globe
  description: 
  - Income tax return filing
  - Tax representation
- name: GST
  page: gst.html
  image: fa-heart
  description: 
  - Registration 
  - Return
  - Compliances
  - e-way bill
